# Section-A

## A1. Why are NumPy arrays generally preferred over plain Python lists for numerical computation in AI/ML?

NumPy arrays are preferred because they are faster for numerical calculations than normal Python lists. They use memory more efficiently and can perform operations on many values at once. NumPy also provides many useful functions for mathematical and statistical operations. These features make it useful for AI/ML data processing.

In [51]:
import numpy as np

In [52]:
#Example Program
numbers = [1, 2, 3]
arr = np.array(numbers)

print(arr * 2)

#Example explanation: NumPy can perform the operation on all array elements at once.

[2 4 6]


## A2. Explain vectorization. Why does replacing an explicit Python loop with a vectorized NumPy operation matter with large datasets?

Vectorization means performing an operation on the whole NumPy array instead of processing each value one by one using a loop. It makes the code shorter and usually faster. For large datasets, vectorized operations can save a lot of processing time. This is why vectorization is commonly used in NumPy and AI/ML.

In [53]:
#Example Program

marks = np.array([20, 30, 40, 50])
result = marks + 10

print(result)

#Example explanation: The same operation is applied to all values without using a loop.

[30 40 50 60]


## A3. For compatible 2D arrays A and B, explain A * B vs A @ B. Describe one neural-network situation for each.

`A * B` performs element-wise multiplication, so corresponding elements are multiplied. `A @ B` performs matrix multiplication, where rows and columns are multiplied according to matrix multiplication rules. Element-wise multiplication can be used for applying a mask or scaling values. Matrix multiplication is commonly used when calculating the output of a neural-network layer using inputs and weights.

In [54]:
#Example Program

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[2, 2],
              [2, 2]])

print(A * B)
print(A @ B)

#Example explanation: * multiplies corresponding elements, while @ performs matrix multiplication.

[[2 4]
 [6 8]]
[[ 6  6]
 [14 14]]


## A4. What is broadcasting in NumPy? State the general rule used to decide whether arrays of different shapes can be combined element-wise.

Broadcasting allows NumPy to perform element-wise operations between arrays having different but compatible shapes. NumPy compares their dimensions starting from the last dimension. Two dimensions are compatible when they are equal or when one of them is 1. This allows smaller arrays to work with larger arrays without manually copying the values.

In [55]:
#Example Program

marks = np.array([10, 20, 30])

result = marks + 5

print(result)

#Example explanation: The value 5 is automatically applied to every element of the array.

[15 25 35]


## A5. Explain flatten() vs ravel(). In a memory-constrained application processing large images, which would you prefer and why?

Both `flatten()` and `ravel()` convert an array into a one-dimensional array. `flatten()` normally creates a new copy of the data, while `ravel()` tries to return a view when possible. Therefore, `ravel()` generally uses less extra memory. For large images with limited memory, I would prefer `ravel()`.

In [56]:
#Example Program

arr = np.array([[1, 2],
                [3, 4]])

print(arr.flatten())
print(arr.ravel())

#Example explanation: Both convert the array into one dimension, but ravel() can avoid creating an extra copy when possible.

[1 2 3 4]
[1 2 3 4]


## A6. For a 2D array, explain axis=0 and axis=1 in an aggregation function such as np.sum() or np.mean().

For a 2D array, `axis=0` means the operation is performed down the rows, giving a result for each column. `axis=1` means the operation is performed across the columns, giving a result for each row.

For example:

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

np.sum(arr, axis=0) gives [5, 7, 9], while np.sum(arr, axis=1) gives [6, 15].

In [57]:
#Example Program

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))

#Example explanation: axis=0 gives the sum of each column and axis=1 gives the sum of each row.

[5 7 9]
[ 6 15]


## A7. Why is it important to normalize or standardize numerical features before training most ML models? Explain normalization vs standardization.

Normalization or standardization makes numerical features have a suitable scale before giving them to a model. This prevents features with large values from having too much influence compared to smaller ones. Normalization usually changes values to a fixed range such as 0 to 1. Standardization changes values based on their mean and standard deviation.

In [58]:
#Example Program

marks = np.array([20, 40, 60, 80, 100])

normalized = (marks - marks.min()) / (marks.max() - marks.min())

standardized = (marks - marks.mean()) / marks.std()

print(normalized)
print(standardized)

#Example explanation: Normalization changes the values to a 0–1 range, while standardization changes them based on the mean and standard deviation.

[0.   0.25 0.5  0.75 1.  ]
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


## A8. Why do functions such as np.nanmean() exist? What happens if np.mean() is used directly on data containing NaN?

`np.nanmean()` is used to calculate the mean while ignoring `NaN` values. If `np.mean()` is directly used on an array containing `NaN`, the result will normally also be `NaN`. Therefore, `np.nanmean()` is useful when some data values are missing.

In [59]:
#Example Program

data = np.array([10, 20, np.nan, 40])

print(np.mean(data))
print(np.nanmean(data))

#Example explanation: np.mean() is affected by NaN, while np.nanmean() ignores the missing value.

nan
23.333333333333332


## A9. In the ML convention X.shape = (samples, features), explain how this extends to a batch of RGB images. Write the exact shape for 64 RGB images of size 128 × 128.

For normal ML data, the shape can be represented as `(samples, features)`. For RGB images, we also need dimensions for height, width, and the three color channels. Therefore, a batch of 64 RGB images of size `128 × 128` has the shape:

(64, 128, 128, 3)

Here, `64` is the number of images and `3` represents the RGB channels.

In [60]:
#Example Program

image = np.zeros((128, 128, 3))

print(image.shape)

images = np.zeros((64, 128, 128, 3))

print(images.shape)

#Example explanation: One RGB image has height, width and 3 channels, while a batch also has the number of images.

(128, 128, 3)
(64, 128, 128, 3)


## A10. Why is reproducibility important during model development and experimentation? Refer to fixing a random seed with np.random.default_rng(seed).

Reproducibility means getting the same random results when the same experiment is run again. It is important because it helps us compare experiments and debug our code. We can use `np.random.default_rng(seed)` with a fixed seed to make the random results repeatable. This makes experiments easier to test and verify.

In [61]:
#Example Program

rng1 = np.random.default_rng(10)
rng2 = np.random.default_rng(10)

print(rng1.random(5))
print(rng2.random(5))

#Example explanation: Both random generators use the same seed, so they produce the same values.

[0.95600171 0.20768181 0.82844489 0.14928212 0.51280462]
[0.95600171 0.20768181 0.82844489 0.14928212 0.51280462]


# SECTION B – PREDICT THE OUTPUT

## B1. Broadcasting – Predict the Shape

import numpy as np

a = np.array([1, 2, 3])

b = np.array([[1], [2], [3]])

print((a + b).shape)

### Predicted Output:

(3, 3)

### Justification:
a has shape (3,) and b has shape (3,1). Broadcasting expands them so the addition produces a (3,3) array.

## B2. Indexing

import numpy as np

x = np.arange(1, 7).reshape(2, 3)

print(x[:, 1])

### Predicted Output:

[2 5]

### Justification:
: means all rows and 1 means the second column. So the values are 2 and 5.

## B3. Boolean Indexing
import numpy as np

arr = np.array([5, 10, 15, 20, 25])

print(arr[arr % 10 == 0])

### Predicted Output:

[10 20]

### Justification:
The condition checks which values are divisible by 10. So 10 and 20 are selected.

## B4. Matrix Multiplication
import numpy as np

m = np.array([[1, 2], [3, 4]])

print(m.T @ m)

### Predicted Output:

[[10 14]
 [14 20]]

### Justification:
First m.T gives the transpose of the matrix. Then @ performs matrix multiplication between m.T and m.

## B5. NaN Handling
import numpy as np

data = np.array([1, 2, np.nan, 4])

print(np.mean(data), np.nanmean(data))

### Predicted Output:

nan 2.3333333333333335

### Justification:
np.mean() includes the NaN, so the result is NaN. np.nanmean() ignores the NaN and calculates the mean of the remaining values.

## B6. Conditional Selection
import numpy as np

x = np.array([10, 20, 30])

y = np.where(x > 15, 1, 0)

print(y)

### Predicted Output:

[0 1 1]

### Justification:
The values greater than 15 get 1 and the values less than or equal to 15 get 0. So the output is [0 1 1].

## B7. Array Properties
import numpy as np

a = np.zeros((3, 4))

print(a.ndim, a.size)

### Predicted Output:

2 12

### Justification:
The array has 2 dimensions because it has rows and columns. It has 3 × 4 = 12 elements.

## B8. Reverse Indexing
import numpy as np

arr = np.arange(1, 13).reshape(3, 4)

print(arr[::-1, ::-1])

### Predicted Output:

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]

### Justification:
[::-1] reverses the order. Here it is used for both rows and columns, so the complete array is reversed.

# SECTION C – CODING / IMPLEMENTATION

## C1. Given a 1D NumPy array of exam scores, use np.where() to produce labels 'P' (score >= 40) or 'F' (score < 40). 

In [62]:
scores = np.array([35, 45, 60, 30, 80])

result = np.where(scores >= 40, 'P', 'F')

print(result)

#Explanation: Here np.where() checks each score. If the score is 40 or more, it gives P, otherwise it gives F.

['F' 'P' 'P' 'F' 'P']


## C2. Write a function standardize(x) that takes a 1D NumPy array and returns its z-score standardized version using only NumPy. 

In [63]:
def standardize(x):
    return (x - np.mean(x)) / np.std(x)

x = np.array([10, 20, 30, 40, 50])

result = standardize(x)

print(result)

#Explanation: The mean is subtracted from each value and then divided by the standard deviation to get the standardized values.


[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


## C3. Given two 2D NumPy arrays representing separate batches with the same number of features, combine them using an appropriate NumPy stacking function and print the resulting shape.

In [64]:
batch1 = np.array([[1, 2], [3, 4]])
batch2 = np.array([[5, 6], [7, 8]])

combined = np.vstack((batch1, batch2))

print(combined)
print(combined.shape)

#Explanation: vstack() combines the two arrays row-wise. The final array has 4 rows and 2 features.

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


## C4. Given X with shape (100, 5), compute column-wise mean and standard deviation and standardize the matrix in one vectorized expression

In [65]:
X = np.random.default_rng(10).random((100, 5))

mean = np.mean(X, axis=0)
std = np.std(X, axis=0)

X_standardized = (X - mean) / std

print(X_standardized.shape)

#Explanation: axis=0 calculates the mean and standard deviation for each column. Broadcasting is then used to standardize the complete matrix.

(100, 5)


## C5. Implement y_pred = X @ w + b for a feature matrix X, weight vector w and bias b. Then compute MSE using y_true. 

In [66]:
X = np.array([[1, 2], [2, 3], [3, 4]])

w = np.array([0.5, 1.0])
b = 2.0

y_true = np.array([4, 6, 8])

y_pred = X @ w + b

mse = np.mean((y_true - y_pred) ** 2)

print("Predicted values:", y_pred)
print("MSE:", mse)

#Explanation: X @ w + b calculates the predicted values. MSE is calculated by taking the mean of the squared difference between actual and predicted values.

Predicted values: [4.5 6.  7.5]
MSE: 0.16666666666666666


## C6. Using np.random.default_rng() with a fixed seed, generate 10 samples and 3 features from a normal distribution. Print the shape and confirm identical results with the same seed.

In [67]:
rng1 = np.random.default_rng(10)
data1 = rng1.normal(size=(10, 3))

rng2 = np.random.default_rng(10)
data2 = rng2.normal(size=(10, 3))

print(data1.shape)
print(np.array_equal(data1, data2))

#Explanation: The shape is (10, 3) because there are 10 samples and 3 features. Using the same seed produces the same random values.

(10, 3)
True


## C7. Given a grayscale image as a 2D NumPy array with pixel values in [0, 255], normalize the values to [0, 1] using min-max normalization. 

In [68]:
image = np.array([[0, 128], [200, 255]])

normalized = (image - image.min()) / (image.max() - image.min())

print(normalized)

#Explanation: The minimum value becomes 0 and the maximum value becomes 1. The other pixel values are converted between 0 and 1.

[[0.         0.50196078]
 [0.78431373 1.        ]]


## C8. Given 4 RGB images of shape (28, 28, 3), stored as shape (4, 28, 28, 3), compute the average pixel value of each image across height, width and channels. State the axis argument and why.

In [69]:
images = np.random.default_rng(10).random((4, 28, 28, 3))

average = np.mean(images, axis=(1, 2, 3))

print(average.shape)
print(average)

#Explanation: axis=(1, 2, 3) means height, width and RGB channels are averaged. So one average value is obtained for each of the 4 images.

(4,)
[0.4989943  0.50477468 0.5037493  0.50337323]


# SECTION D – APPLIED SCENARIOS

## D1. Data Preprocessing Pipeline

We have a NumPy array containing NaN values. The steps are:

1.Detect the missing values using np.isnan().

2.Find the mean of the available values using np.nanmean().

3.Replace the missing values with the mean.

4.Standardize the cleaned data using mean and standard deviation.

In [70]:
data = np.array([10, 20, np.nan, 40, 50])

# Detect missing values
missing = np.isnan(data)
print("Missing values:", missing)

# Find the mean without considering NaN
mean_value = np.nanmean(data)

# Replace NaN with the mean
data[missing] = mean_value
print("Cleaned data:", data)

# Standardize the clean data
standardized = (data - np.mean(data)) / np.std(data)

print("Standardized data:", standardized)

Missing values: [False False  True False False]
Cleaned data: [10. 20. 30. 40. 50.]
Standardized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


### Explanation:
np.isnan() is used to find the missing values. I used np.nanmean() to calculate the mean without including NaN, and replaced the missing value with this mean. Finally, the cleaned data is standardized using its mean and standard deviation.

### Justification:
I used mean replacement because it keeps the data and does not remove the value completely. After handling the missing value, the data can be standardized before giving it to the model.

## D2. Image Batch Understanding

A single RGB image has the shape:

(height, width, channels)

For a 64 × 64 RGB image:

(64, 64, 3)

Here 3 represents the RGB channels.

A batch of RGB images has one extra dimension for the number of images:

(number of images, height, width, channels)

For 16 images:

(16, 64, 64, 3)

In [71]:
# Create a batch of 16 RGB images
images = np.random.default_rng(10).random((16, 64, 64, 3))

print("Batch shape:", images.shape)

# Calculate the average image
average_image = np.mean(images, axis=0)

print("Average image shape:", average_image.shape)



Batch shape: (16, 64, 64, 3)
Average image shape: (64, 64, 3)


### Explanation:
The batch contains 16 images, and each image has 64 height, 64 width and 3 RGB channels. axis=0 calculates the mean across all 16 images, so the first dimension is removed.

### Justification:
I used axis=0 because I want to calculate the average of all images while keeping the height, width and RGB channels the same.

## D3. Debug the Model Code

The given code contains more than one bug.

In [72]:
X = np.array([[1, 2],
              [2, 3],
              [3, 4]])

w = np.array([0.5, 1.0])

b = 2.0

y_true = np.array([10, 20, 30])

y_pred = X @ w + b

mse = np.mean((y_true - y_pred) ** 2)

print("Predicted values:", y_pred)
print("MSE:", mse)

Predicted values: [4.5 6.  7.5]
MSE: 244.16666666666666


## Bug 1 – Weight Shape

X has shape (3, 2), which means there are 3 samples and 2 features.

But w has shape (3,), so it contains 3 weights.

For X @ w, the number of features in X must match the number of values in w.

So w should contain 2 weights.

## Bug 2 – MSE Formula

The given formula is:

np.mean(y_true - y_pred ** 2)

Because of operator precedence, y_pred ** 2 is calculated first.

So it is actually calculating:

np.mean(y_true - (y_pred ** 2))

For MSE, we need to first find the difference between actual and predicted values, then square the complete difference:

np.mean((y_true - y_pred) ** 2)

In [73]:
X = np.array([[1, 2],
              [2, 3],
              [3, 4]])

w = np.array([0.5, 1.0])

b = 2.0

y_pred = X @ w + b

y_true = np.array([10, 20, 30])

mse = np.mean((y_true - y_pred) ** 2)

print("Predicted values:", y_pred)
print("MSE:", mse)



Predicted values: [4.5 6.  7.5]
MSE: 244.16666666666666


### Explanation:
X has 2 features, so w must have 2 values. The MSE formula also needs parentheses so that the complete difference between y_true and y_pred is squared before calculating the mean.

### Justification:
The first bug is the mismatch between the number of features and weights. The second bug is the missing parentheses in the MSE formula, because the complete prediction error should be squared.

## E1. Per-Column Min-Max Normalization

Implement min-max normalization for each column separately in a 2D feature matrix.

# SECTION E – BONUS / CHALLENGE

In [74]:
X = np.array([[10, 100],
              [20, 200],
              [30, 300],
              [40, 400]])

min_value = np.min(X, axis=0)
max_value = np.max(X, axis=0)

normalized = (X - min_value) / (max_value - min_value)

print(normalized)


[[0.         0.        ]
 [0.33333333 0.33333333]
 [0.66666667 0.66666667]
 [1.         1.        ]]


### Explanation:
axis=0 finds the minimum and maximum values separately for each column. Then each column is normalized between 0 and 1.

### Justification:
I used axis=0 because the normalization should be done separately for each feature column.

## E2. Three-Level Score Classification

Classify the scores into three levels:

1. Fail → score < 40

2. Average → 40 to 70 inclusive

3. Excellent → score > 70

In [75]:
scores = np.array([25, 40, 55, 70, 85])

result = np.where(scores < 40, 'Fail',
                  np.where(scores <= 70, 'Average', 'Excellent'))

print(result)


['Fail' 'Average' 'Average' 'Average' 'Excellent']


### Explanation:
The first np.where() checks for scores below 40. The second np.where() checks whether the remaining scores are 70 or below, and the remaining scores are classified as Excellent.

### Justification:
I used nested np.where() so all three categories can be classified without using if-else or loops.